### ISSUE TITLE
No Readme.

### ISSUE THREAD

**Issue by etaletai13** [darknoon29/OFI#1]
This is quite the confusion, without a readme to guide or at least some sort of build script. What is needed to build this?

**Comment by darknoon29** [comment]
Yes you're completly right.
This tool is built against Visual Studio.

But to get Data it connects to OGSpy on an API that does not exists anymore.

**Comment by etaletai13** [comment]
Ahhhh, that makes some sense. Is this something you'd like to revive and have some support in?

**Comment by darknoon29** [comment]
Yes we would like to revive this project and the first step would be to create an API on OGSpy side. We can discuss on slack or discord about this. https://forum.ogsteam.fr for all links.

**Comment by etaletai13** [comment]
Alright, thanks!
